import React from 'react';
import useStars from '../hooks/useStars';

/**
 * Test component for useStars hook.
 */
const TestUseStars = () => {
  const width = 1920; // Hardcoded test dimensions
  const height = 1080;
  const density = 0.001;

  const positions = useStars(width, height, density);

  console.log('useStars returned positions:', positions);

  return (
    <div>
      <h1>Check the console for positions generated by useStars</h1>
    </div>
  );
};

export default TestUseStars;
